[tool.poetry]
name = "stratosurfer-tail-design"
version = "0.0.0"
description = ""
authors = ["Matt Marti <matthew.marti@gmail.com>"]

[tool.poetry.dependencies]
python = "3.8"
numpy = "^1.22.2"
scipy = "^1.8.0"
matplotlib = "^3.5.1"
pyyaml = "*"

[tool.poetry.dev-dependencies]
jupyter = "^1.0.0"